
@base=https://johna69-simplest-deployment.cfapps.us10-001.hana.ondemand.com
@grok=https://0a5d-165-1-200-70.ngrok-free.app

# Test Server
###
#
GET https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester

###
# $metadata
GET https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/$metadata

###
# Testlog all users  
GET https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/Testlog

###
# Testlog my users  
GET https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/Testlog?$filter=communityid eq 'johna69'

###
# Test Task 1
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/basic",
  "task": "basic-ping"
}

###
# Test Task 2
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/basic",
  "task": "basic-hello"
}

###
# Test Task 3
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/basic",
  "task": "basic-sum"
}

###
# Test Task 4
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/rest/plain",
  "task": "plain-theAnswer"
}

###
# Test Task 5
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/rest/plain",
  "task": "plain-serviceDocument"
}

###
# Test Task 6
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{base}}/rest/plain",
  "task": "plain-highestValue"
}

###
# Test Task 7
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{grok}}/odata/v4/northbreeze",
  "task": "northbreeze-productInfo"
}

###
# Test Task 8
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{grok}}/odata/v4/northbreeze",
  "task": "northbreeze-Products"
}

###
# Test Task 9
POST https://developer-challenge-2024-07.cfapps.eu10.hana.ondemand.com/tester/testServer
content-type: application/json
  
{
  "communityid": "johna69",
  "serviceurl": "{{grok}}/odata/v4/northbreeze",
  "task": "northbreeze-selectProduct"
}


# Testee
###
# Access the base URL
GET {{base}}

###
# Service Document
GET {{base}}/odata/v4/catalog

###
# Metadata
GET {{base}}/odata/v4/catalog/$metadata

###
# Books
GET {{base}}/odata/v4/catalog/Books

### 
# Test Ping
GET {{base}}/basic/ping()

### 
# Test hello
GET {{base}}/basic/hello(to='Zaphod')

### 
# Test theAnswer
GET {{base}}/rest/plain/theAnswer

### 
# Test highestValue
POST {{base}}/rest/plain/highestValue
Content-Type: application/json

[1,2,3,-4,-9,5]

### 
# Product Info
GET {{base}}/odata/v4/northbreeze/productInfo(id=11)

# Local

###
#
GET http://localhost:4004/

### 
# Test Ping
GET http://localhost:4004/basic/ping()

### 
# Test Hello
GET http://localhost:4004/basic/hello(to='Zaphod')


### 
# Test Sum
GET http://localhost:4004/basic/sum(a=1,b=4)

### 
# Test theAnwer
GET http://localhost:4004/rest/plain/theAnswer

### 
# Test highestValue
POST http://localhost:4004/rest/plain/highestValue
Content-Type: application/json

[1,2,3,-4,-9,5]


### 
# Product Info
GET http://localhost:4004/odata/v4/northbreeze/productInfo(id=11)

### 
# Product Info
GET {{grok}}/odata/v4/northbreeze/productInfo(id=11)

### 
# Test selectProduct
POST http://localhost:4004/odata/v4/northbreeze/selectProduct
Content-Type: application/json

{"communityid":"johna69"}

### 
# Test selectProduct
POST {{grok}}/odata/v4/northbreeze/selectProduct
Content-Type: application/json

{"communityid":"johna69"}